/**
 * Centralized machine-readable error codes for client-side consumption.
 */
export const ErrorCodes = {
  // Auth & Access
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  
  // Validation & Input
  INVALID_INPUT: 'INVALID_INPUT',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  
  // User & Profile
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  KYC_REQUIRED: 'KYC_REQUIRED',
  
  // Features
  MATCH_REQUIRED: 'MATCH_REQUIRED',
  DUPLICATE_SWIPE: 'DUPLICATE_SWIPE',
  USER_NOT_AVAILABLE: 'USER_NOT_AVAILABLE',
  
  // Premium & Payments
  UPGRADE_REQUIRED: 'UPGRADE_REQUIRED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  
  // System
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  NOT_FOUND: 'NOT_FOUND',
};

export default ErrorCodes;
